Tweet.destroy_all
TwitterAccount.destroy_all
User.destroy_all
TweetWord.destroy_all
TwitterFollowerRelationship.destroy_all

# kate = User.create(email: "katy@katy.com", password: "password", name: "Katy Perry")
# kate.build_twitter_account(twitter_id: "1234").save
# kate.twitter_account.tweets.create([
#   {tweet_text: "i n t e r m i s s i o n"},
#   {tweet_text: "Full circle: playing the 1st song I wrote for the album to close out PRISM. Dont miss #ByTheGraceofGod my most personal song, on @TheGRAMMYs"},
#   {tweet_text: "Any distribution or purchase of these type of photos anywhere is extremely against my will &amp; is an endangerment to me &amp; my family's privacy."},
#   {tweet_text: "Remember internet it's literally ILLEGAL to post pictures of me at my house w/my family that unethical paparazzi have taken on long lenses."},
#   {tweet_text: "Also shout out to this guy who loved the Sharks so much he drew blood for them 👊 http://t.co/F89tfeKVq6"},
#   {tweet_text: "THE SHARKS FROM THE SUPER-BOWL SIT DOWN W/@JohnMayer WHO'S GUEST HOSTING THE LATE LATE SHOW ON CBS TONIGHT @ 12:35AM/11:35PM CT #leftshark"},
#   {tweet_text: "And last but not least, GUANGZHOU completes the Asia tour! http://t.co/rVy2OGtQZw #PrismaticWorldTour"},
#   {tweet_text: "More ASIA dates for you at http://t.co/l3WgZjMZaS! See you soon Shanghai, Macao and Singapore! #PrismaticWorldTour"},
#   {tweet_text: "Bleach ya brows and call it FASHUN. 💁"},
#   {tweet_text: "Fashion! = adorable Giambattista Valli set and Chanel earrings 😍 Third time, and it's still a charm, @ELLEmagazine! http://t.co/5kebJA6VQh"},
#   {tweet_text: "Night' http://t.co/CffDndSzS7"},
#   {tweet_text: "MOST WATCHED SHOW IN US HISTORY?! Whelp, I gotta keep reminding myself I put my pants on leg at a time... But, yes I am incredibly proud!"},
#   {tweet_text: "Mark your calendars! The Prismatic World Tour will premiere on March 28th at 8:00 PM ET on @EpixHD! #PrismaticOnEPIX http://t.co/iTluCfAxfJ"},
#   {tweet_text: "🔥XLIX🔥 http://t.co/Qa0chE8Yv0"},
#   {tweet_text: "I thought it would be appropriate to draw blood tonight... XLIX 🔥 http://t.co/j75uTsjka9"},
#   {tweet_text: "GUYS! Want the guitars that my band will be playing at #SB49? Bid now to benefit @BreaktheCycleDV: http://t.co/EnqczPrVI8 🎸🏈🎸🏈"},
#   {tweet_text: "Today is for this girl. She had the dream, always believed in herself &amp; her worth. Today she is the one smiling. http://t.co/9jMh3hWubz"},
#   {tweet_text: "🙏 Today is the day that the Lord has made! I will rejoice and be glad in it! 🙏"},
#   {tweet_text: "...Also if u wanna complete the lewk w/the necklace &amp; earrings I wore to the press conference! http://t.co/6mZC2U70kz http://t.co/YnXLp8y5il"},
#   {tweet_text: "OMG I made dis offish fuzzy sweater dress! buy RIGHT NOW @ NFL EXPERIENCE in PHX or pre-order http://t.co/q11Z1UV5JV http://t.co/FFzDBcuyen"},
#   {tweet_text: "#FBF to that one time I was hanging out in the Seahawks' locker room... http://t.co/zHnOVeTavk"},
#   {tweet_text: "BILLBOARD. On stands tomorrow! ❤️🇺🇸🏈❤️🇺🇸🏈❤️🇺🇸🏈 http://t.co/b8FOxwwvvH"},
#   {tweet_text: "When someone says for you to \"stay in your lane\" just respond, \"THIS IS MY HIGHWAY BISH!\" 💁"},
#   {tweet_text: "If only I could have Mickey n Minnie on stage too 🙍 http://t.co/BB3lH8lYHV http://t.co/clKa0hF5mH"},
#   {tweet_text: "What I don't have in thigh gap-ness I make up in eyebrow arch 💁"},
#   {tweet_text: "Because: 🏈 http://t.co/zHNs52PTFa"},
#   {tweet_text: "And for the rest of the world, PATIENCE is the key 😉"},
#   {tweet_text: "Up next: TAIPEI - I'll see you April 28! MANILA - You're on May 7! JAKARTA - I'm coming back May 9! BANGKOK - get prismatic with me May 14!"},
#   {tweet_text: "First up, TOKYO, April 25 &amp; 26! http://t.co/l3WgZk4AiW"},
#   {tweet_text: "Just when you thought the #PrismaticWorldTour was over, I'm pleased to announce that I'll be bringing it to ASIA this April and May!"},
#   {tweet_text: "Let's just say I am dressed for the ball today... tune in on @nflnetwork #SB49 #🏈"},
#   {tweet_text: "Even my tippy toes are ready #🏈 http://t.co/JrqbZ32f6P"},
#   {tweet_text: "🙍SuPeR BoWl LeAk🙍http://t.co/Y5JnJ21YBG"},
#   {tweet_text: "WHAT A TRAP 🙅 http://t.co/2VMUPG9KJN"},
#   {tweet_text: "My dream for after SB is to have a procession of chilled Girl Scout thin mint cookies brought to me by Girl Scouts w/sparklers a la da club."},
#   {tweet_text: "WHAT I DON'T HAVE IN ABS, I MAKE UP FOR IN HEART!"},
#   {tweet_text: "YAS MJ YAS!!! SLAY MJ SLAY!!! HE HOLDS FOR APPLAUSE FOR A MINUTE &amp; 30 SECONDS &amp; MOVES ONCE! SLAYYY FOR THE GODS http://t.co/f59sm3f9yX"},
#   {tweet_text: "Having a great rehearsal, hope everyone has a great Friday!!! #🏈 http://t.co/q1nfp53xLm"},
#   {tweet_text: "V important puppy bowl meeting 🐶🏈 http://t.co/6S9fdfyMG0"},
#   {tweet_text: "Wore my slides to a FASHUN party tonight because @ITSJEREMYSCOTT 💁 http://t.co/xAbP8q5KZn"},
#   {tweet_text: "LATE http://t.co/02PeWzeEhR"},
#   {tweet_text: "http://t.co/lT05bvtqql"},
#   {tweet_text: "Let's go wide on that cover shot for @espnmag shall we @jjwatt http://t.co/S2MbFzb07d"},
#   {tweet_text: "Just finished a killer workout! Have a great day y'all 👍 http://t.co/8smUnelXw3"},
#   {tweet_text: "Hey @JJWatt what do you think of our @ESPNMag cover? TOUCHDOWN?! 🏈❤️🏈❤️🏈❤️🏈❤️🏈❤️ http://t.co/ibGTW8tL7p"},
#   {tweet_text: "Playing so many bowls this year. So scressful. http://t.co/ixd8nVhORK"},
#   {tweet_text: "GIRL SCOUT COOKIE SEASON IS LITERALLY CIRCLING MY SUPER BOWL BODY DEBUT. WHAT A SET UP! 👿"},
#   {tweet_text: "when u hit the blunt too hard butters http://t.co/KGVZQnL6hd"},
#   {tweet_text: "I want to be the Lucille Ball of pop music..."},
#   {tweet_text: "👗FASHIONISTAS👗check http://t.co/cphiCBPsTS for Q-T vintage finds &amp; rad new clothes. Follow them on Twitter @lonelydot IG: lonelydot ❤️"},
#   {tweet_text: "IRL facetune #preppinforpuppybowl #swag #bringswagbackin2k15 http://t.co/F0tcb8W07I"},
#   {tweet_text: "OK! Found a new jam to share for the new year: Desire by Years &amp; Years \nhttp://t.co/foSVlLmiGk ❤️🎶❤️🎶❤️🎶 more please!"},
#   {tweet_text: "Deep in SB rehearsals: http://t.co/2hXe5DzqeT"},
#   {tweet_text: "Eagerly looking forward to the first big musical contribution of 2015 that just knocks me off my feet... Who's gonna take the title?!?!"},
#   {tweet_text: "Science says 🙍 http://t.co/QX8VMelwMi"},
#   {tweet_text: "ICYMI RT @nfl:Joining @KatyPerry during her @pepsi @superbowl #halftime show on @SNFonNBC? \nMr @LennyKravitz. \nFeb 1 can’t come soon enough!"},
#   {tweet_text: "I have a big surprise announcement coming up at #halftime of this @Ravens-@Patriots game! Make sure you're 👀📺! 🏈 🎤 🎸"},
#   {tweet_text: "If Sophia Grace plays her new trap hit at Coachella... I'll go. cc @yungskeeter @sofifii"},
#   {tweet_text: "Sweet dreams habibis http://t.co/qvlyNBDSgn"},
#   {tweet_text: "Did some 💄🎨MAJE🎨💄werk w/THEE @patmcgrathreal today for @covergirl! We had quite the… http://t.co/OH32R8Xiit"},
#   {tweet_text: "Current mood: Speak if it only improves upon the silence - Mahatma Gandhi"},
#   {tweet_text: "Happy New Year. I love a fresh start."},
#   {tweet_text: "Ok! http://t.co/gpqdCaGtb5"},
#   {tweet_text: "I got so many mophies and lash glue for everyone. Come at me 2015, I'm ready."},
#   {tweet_text: "6th train squad game strongé 💪 http://t.co/ULjBX4EHNn"},
#   {tweet_text: "Reflective."},
#   {tweet_text: "Tip for tomorrow: remember to consider everyone's face when posting group photos!"},
#   {tweet_text: "#OOTW!!! I hope it's not too late to get best dressed 2k14 😬Thanks to my friends @belovedshirts for… http://t.co/fdc0cwcXBI"},
#   {tweet_text: "YOU ARE MY EMOTIONAL EPI PEN cc: @sofifii 💉"},
#   {tweet_text: "。 ° · 。 · ˚ ˚ ˛ ˚ ˛\n。° 。 ° 。˚ ˛ · ˚ ˚ ˛\n★MERRY★ 。 · ˚ ˚ \n。CHRISTMAS 。 \n_Π_＿ 。 ˚ ˚ ˛ ˚ ˛\n/____＿/ ＼。˚ ˚ ˛ ˚\nl田田田 |門| ˚ ˛ ˚ ˛ ·\n2 all my BB's!"},
#   {tweet_text: "My parents are on my last Christmas nerve 🙍🎄 http://t.co/GQisVtMSVV"},
#   {tweet_text: "Don't have enough treats for ur stocking! Well these rubber bb's are now back in stock!🎅🍕🍔🍕🎅 http://t.co/5Kt67Zc72r http://t.co/pG5Fy7ZFD3"},
#   {tweet_text: "I'm dreaming of a right Christmas..."},
#   {tweet_text: "Mornin friends! Time to huddle up! Go to http://t.co/uaWjIzE1aw &amp; enter for a chance to see me @ the Pepsi Super Bowl XLIX Halftime Show! 🏈🙌"},
#   {tweet_text: "Nothing says I love you like a bowl of spaghetti bolognese 🍝"},
#   {tweet_text: "Taking a 🎅🎄break🎄🎅 from the #PrismaticWorldTour but come take a peek backstage w/ me &amp; @ferras: http://t.co/x4V4qocoGX"},
#   {tweet_text: "A casual sleighing w/santa 💁🎅 http://t.co/6AE4GFHbr5"},
#   {tweet_text: "Tbh I get really turned on when people rsvp correctly."},
#   {tweet_text: "hi http://t.co/dj6gCb0otn"},
#   {tweet_text: "Hakuna Matata bitches 💁 http://t.co/Ld8JQuKPRg"},
#   {tweet_text: "One of the most beautiful, vulnerable, REAL things I have ever seen, spoken like a proverb @Beyonce http://t.co/4aYt0CZ7rQ"},
#   {tweet_text: "SYDNEY! Tonight &amp; tomorrow we'll b capturing the magic of #ThePrismaticWorldTour for the 📺MAKE SURE 2 WERK DEM CAMERAS BB'S! SCREAM! SMIZE!"},
#   {tweet_text: "Saw the most exquisite production of The Nutcracker by the Australian Ballet at The Sydney Opera house! Finally, it feels like Christmas 🎅"},
#   {tweet_text: "Even though you know it's gonna be a safe flight, there's just comfort in someone telling you that. #itsthelittlethings"},
#   {tweet_text: "SAFE FLIGHT @sofifii"},
#   {tweet_text: "Relationship goals: http://t.co/OhVMmSUcfe"},
#   {tweet_text: "Eye on the prize not on the fries #SuperBowl 🙍"},
#   {tweet_text: "OOTD school girl raincoat vibez http://t.co/eB89AFIA1W"},
#   {tweet_text: "The man responsible for all things maritime stripes &amp; more: ⚓️Jean Paul Gaultier⚓️@ngvmelbourne @… http://t.co/d6qHMv9Onq"},
#   {tweet_text: "RT if your favorite jelly belly is juicy pear."},
#   {tweet_text: "It's the last game of the day, but you can still get #HypedForHalftime with my 🏈-inspired #iTunesRadio playlist: https://t.co/nyJMOQrkIn 🙌"},
#   {tweet_text: "#tiestoinaustralia http://t.co/HpcliAPR02"},
#   {tweet_text: "Very cool way to wake up w/2 noms for the @TheGRAMMYs s/o to my bro @therealjuicyj for the collab nom! Imagine if I win for a trap record! 😳"},
#   {tweet_text: "WHOAH my little niña @iambeckyg is growing up right before my eyes 😩 https://t.co/JOk7mHrWPo"},
#   {tweet_text: "So ❤️ that you guys are listening to these songs! 🎶🎧 https://t.co/haZp3EMSiL"},
#   {tweet_text: "I BELIEVE IN YOU ALLISON WILLIAMS!!!"},
#   {tweet_text: "If I could, I would be there laying in those streets of NYC, peacefully protesting. WE HAVE TO CHANGE. ALL LIVES MATTER #WeCantBreathe"},
#   {tweet_text: "Tonight in Melbourne we play our 100th show on #ThePrismaticWorldTour! I am SO proud &amp; I think some ppl are noticing: http://t.co/Tp1clu0paV"},
#   {tweet_text: "Congratulations to my parents Keith &amp; Mary Hudson for on this day 35 years ago they were married &amp; continue to be a love I look up to! ❤️"},
#   {tweet_text: "OOTD @ Future Beauty: 30 years of Japanese Fashion @ The GOMA http://t.co/CyZzj5iJto"},
#   {tweet_text: "OMG THEE @iamtovelo joins #ThePrismaticWorldTour tonight!!! Currently one of my FAVORITE songwriters! My👂are so pleased!"},
#   {tweet_text: "Someone said to me today that I was a spiritual being having a human experience. I love this &amp; agree ✨"},
#   {tweet_text: "EMPATHY ADDICTS cc: @sofifii"},
#   {tweet_text: "Ugh. Another cold in summer. Makes no sense! 😷"},
#   {tweet_text: "Food so good it makes you shake ur leg🍗"},
#   {tweet_text: "BUT I am SO thankful to be on this incredible worldwide journey seeing people filled w/joy night after night. Happy THANKSgiving everyone! 🍗"},
#   {tweet_text: "Just had 1st FaceTime Thanksgiving! What I would give 2b scraping marshmallow off of sweet potato, wearing fuzzy socks &amp; holding my niece! 😩"},
#   {tweet_text: "SYDNEY! I'll b back, but my pop-up shop won't 😩 LAST DAY to shop exclusive Oz merch TODAY! 624 George St, 10a-6p http://t.co/8DWf8Dm5Yu"},
#   {tweet_text: "What a warm welcome from Brisbane! http://t.co/BPGJeNJkdQ"},
#   {tweet_text: "\"Katy Perry, quite contrary, how do your lashes grow?\" #GoBloom like a @COVERGIRL: http://t.co/kdZbw9eNeX"},
#   {tweet_text: "Gonna roll up to the carpet in dis whip http://t.co/vaEFyZs3Kf"},
#   {tweet_text: "Peep my couture outfit fer tonight's @ARIA_Official awards, a #TWISTIE 😂  (Oz's cousin to the cheeto fyi) http://t.co/cT1aPf7sLR"},
#   {tweet_text: "Chicken noodle soup &amp; chamomile tea cause: throat... 😑 Gonna need you more than ever tonight Sydney. Show #95 #ThePrismaticWorldTour"},
#   {tweet_text: "Feeling stuck all the way over here in Sydney seeing the news just now... Sending my prayers to Ferguson &amp; praying for an equal America."},
#   {tweet_text: "FOR IMMEDIATE RELEASE: Pls keep the fruit out of the stuffing!"},
#   {tweet_text: "3 AMA'S &amp; SUPER BOWL?! Not long ago I was playing guitar on the streets of Santa Barbara for maybe 20 bucks a day &amp; an avocado. Wow, life!"},
#   {tweet_text: ".@SNFonNBC @NFL Yeppers! And I've already started testing out ideas! http://t.co/eYUKcQTxtG #halftime"},
#   {tweet_text: "My band is in the other room screaming at the TV (and each other) over this Cowboys-Giants game. Can’t wait for February 1st... 🎤🏈"},
#   {tweet_text: "SQUAD DAY🚢🌉 http://t.co/GRDsfIaFo6"},
#   {tweet_text: "I DID IT. Finally, after all these years talkin bout it I done climbed your bridge tonight Sydney!… http://t.co/awnjnXbHOK"},
#   {tweet_text: "Also remember Jamie Fawcett we hv pictures of ur tiny penis &amp; rather large gut. Ur a true sicko for taking pictures of us while being naked."},
#   {tweet_text: "Remember AUS anyone printing or posting unauthorized photos of me in a bikini from these DISGUSTING/PERVERTED OLD MEN is AGAINST my will!"},
#   {tweet_text: "He soy famo with no name-o tho 😳 http://t.co/e8OnnPYG0x"},
#   {tweet_text: "Fresher than yewww"},
#   {tweet_text: "OZ pre show ritual. 30 mins on the elliptical = 30 minutes of Kath &amp; Kim 😂 http://t.co/uwgH8fTM2v"},
#   {tweet_text: "THESE ARE A FEW OF THE STALKERS: http://t.co/1JtHSIVuqc"},
#   {tweet_text: "http://t.co/rm7kL37Bj2"},
#   {tweet_text: "Yep. I sure did pop in to my pop up store unannounced today in Sydney. I think the customers just… http://t.co/2Tv6CPEkt7"},
#   {tweet_text: "Sometimes the cherry on top is the nail in the coffin."},
#   {tweet_text: "SOTD: I Got You @DukeDumont \nhttps://t.co/8Rqk4ab9un ❤️🙌❤️🙌❤️"},
#   {tweet_text: "CATS! #KPPopUp is moving to Sydney! Pop in to The Lair at Metro Theatre (624 George St) starting tomorrow, Nov 21st-28th 10:00a-6:00p!"},
#   {tweet_text: "G2G my whip is here 💁 http://t.co/mAB0RTyv0l"},
#   {tweet_text: "#GlobalCellSabbath ?"},
#   {tweet_text: "Personally. Wish there was a global cell sabbath every week so we could all breath again..."},
#   {tweet_text: "Remember a time when we didn't have cell phones but had personal space? Now if you don't reply or aren't constantly avail people take it..."},
#   {tweet_text: "The doc FED UP should be found under the horror section in films cause it's SCARY what sugar is doing to our bodies: https://t.co/c3jFPfKesx"},
#   {tweet_text: "Also we landed on a comet y'all 🚀🌠"},
#   {tweet_text: "Feeling v Lolita rn http://t.co/1aI1BKSchB"},
#   {tweet_text: "Fantastic 1st day in Melb! Got 2 deliver a check 2 a girls school, pop in to my pop up &amp; see the HIGHlarious new play Calpurnia Descending!"},
#   {tweet_text: "...just popped in to my pop up shop unannounced in Melbourne!!! Let's just say it won't be the last time... 👀#KPPopUp"},
#   {tweet_text: "Tbh I don't really trust people that continually look down the barrel of a paparazzi lens"},
#   {tweet_text: "Also you never know who might do a pop in to the pop up..."},
#   {tweet_text: "AUSSIES My 1st pop-up shop is NOW open in Melb! Exclusive merch &amp; props from Hello Katy &amp; California Dreams Tours @ 361 Little Lonsdale St!"},
#   {tweet_text: "Purposefully spaced out my consumption of OITNB so that I wouldn't starve till 2015 but den I came to AUS...no netflix zone🙅 #missupiper"},
#   {tweet_text: "Rt if your mom is all about fwding email chain letters on varied conspiracies."},
#   {tweet_text: "HAPPY BIRTHDAY 🍤"},
#   {tweet_text: "Sunburnt in November."},
#   {tweet_text: "Australian jet lag got me like http://t.co/kriAAd6mZe"},
#   {tweet_text: "Mornin' http://t.co/xITxepPHrS"},
#   {tweet_text: "MY Claire Bear helped me kick off my Australian tour tonight in the most PERTH-fect place. Where will… http://t.co/MGD7sLDHfJ"},
#   {tweet_text: "Guys Meet my adorb teddy bear's lil sis Claire Bear, now available at Claire's as part of my 12… http://t.co/3Q3eqLj8Re"},
#   {tweet_text: "Lots of Aussies askin \"who\" is opening up for me on this leg, @BettyWho that's who! Don't miss ur own Aussie @ 7:30!"},
#   {tweet_text: "PERRY + PERTH = 🎉PARTY🎉"},
#   {tweet_text: "S/O to all the people I don't f*ck wit: http://t.co/VD0aajpn5j 👀"},
#   {tweet_text: "Admitting fault = one gold wisdom star for your life chart."},
#   {tweet_text: "Be weary of watching The Truman Show if there is a possibility your life could be the Truman Show 😳"},
#   {tweet_text: "I love this! This is the approach! http://t.co/PcXVPXJMYT"},
#   {tweet_text: "#TBT to when I was a sad cheeto that no one wanted to cuddle at the end of the night🙍🔥 http://t.co/nz0SPGH6UD"},
#   {tweet_text: "I got you a cryo sleeping bag for Christmas, u are gonna have the best nap of ur lyfe dawg @sofifii #nappingisanartform"},
#   {tweet_text: "WHERE ARE THOSE CRYO SLEEPING BAGS FROM INTERSTELLAR IM TRYNA BEAT THIS JET LAG"},
#   {tweet_text: "Michael Jackson always in deez Aussie streets http://t.co/xRi3VpmRZJ"},
#   {tweet_text: "rt if u used to wear love spell"},
#   {tweet_text: "TWO SUMMERS IN ONE YEAR?! THANKS AUSTRALIA!🌴☀️🍗🎅☀️🌴"},
#   {tweet_text: "🙏 heaven is a place on earth 🙏 http://t.co/BcKOCys75p"},
#   {tweet_text: "The more fuzzy stuff you wear the more he'll think you're an actual teddy bear."},
#   {tweet_text: "hi http://t.co/ihlaO8XyUF"}
# ])
