Tweet.destroy_all
TwitterAccount.destroy_all
User.destroy_all
TweetWord.destroy_all
TwitterFollowerRelationship.destroy_all
StopWord.destroy_all

StopWord.create([
  {word: "ve"},
  {word: "a"},
  {word: "about"},
  {word: "above"},
  {word: "after"},
  {word: "again"},
  {word: "against"},
  {word: "all"},
  {word: "am"},
  {word: "an"},
  {word: "and"},
  {word: "any"},
  {word: "are"},
  {word: "aren"},
  {word: "as"},
  {word: "be"},
  {word: "because"},
  {word: "been"},
  {word: "before"},
  {word: "being"},
  {word: "below"},
  {word: "between"},
  {word: "both"},
  {word: "but"},
  {word: "by"},
  {word: "can"},
  {word: "cannot"},
  {word: "could"},
  {word: "couldn"},
  {word: "did"},
  {word: "didn"},
  {word: "do"},
  {word: "does"},
  {word: "doesn"},
  {word: "doing"},
  {word: "don"},
  {word: "down"},
  {word: "during"},
  {word: "each"},
  {word: "few"},
  {word: "for"},
  {word: "from"},
  {word: "further"},
  {word: "had"},
  {word: "hadn"},
  {word: "has"},
  {word: "hasn"},
  {word: "have"},
  {word: "haven"},
  {word: "having"},
  {word: "he"},
  {word: "ll"},
  {word: "her"},
  {word: "here"},
  {word: "hers"},
  {word: "herself"},
  {word: "him"},
  {word: "himself"},
  {word: "his"},
  {word: "how"},
  {word: "if"},
  {word: "in"},
  {word: "into"},
  {word: "is"},
  {word: "isn"},
  {word: "it"},
  {word: "its"},
  {word: "itself"},
  {word: "let"},
  {word: "me"},
  {word: "more"},
  {word: "most"},
  {word: "mustn"},
  {word: "my"},
  {word: "myself"},
  {word: "no"},
  {word: "nor"},
  {word: "not"},
  {word: "of"},
  {word: "off"},
  {word: "on"},
  {word: "once"},
  {word: "only"},
  {word: "or"},
  {word: "other"},
  {word: "ought"},
  {word: "our"},
  {word: "ours"},
  {word: "ourselves"},
  {word: "out"},
  {word: "over"},
  {word: "own"},
  {word: "same"},
  {word: "shan"},
  {word: "she"},
  {word: "should"},
  {word: "shouldn"},
  {word: "so"},
  {word: "some"},
  {word: "such"},
  {word: "than"},
  {word: "that"},
  {word: "the"},
  {word: "their"},
  {word: "theirs"},
  {word: "them"},
  {word: "themselves"},
  {word: "then"},
  {word: "there"},
  {word: "these"},
  {word: "they"},
  {word: "this"},
  {word: "those"},
  {word: "through"},
  {word: "to"},
  {word: "too"},
  {word: "under"},
  {word: "until"},
  {word: "up"},
  {word: "very"},
  {word: "was"},
  {word: "wasn"},
  {word: "we"},
  {word: "re"},
  {word: "were"},
  {word: "weren"},
  {word: "what"},
  {word: "when"},
  {word: "where"},
  {word: "which"},
  {word: "while"},
  {word: "who"},
  {word: "whom"},
  {word: "why"},
  {word: "with"},
  {word: "won"},
  {word: "would"},
  {word: "wouldn"},
  {word: "you"},
  {word: "your"},
  {word: "yours"},
  {word: "yourself"},
  {word: "yourselves"}
  ])

APIKey.create!([
  {access_token: "9e409d4b42e7ab24035d7a819759a6c2", user_id: 1},
  {access_token: "644c59391adfffcfa1999e3b7a6ea07d", user_id: 1}
])
Tweet.create!([
  {tweet_text: "lajsdf o aoioaije aijpao", twitter_account_id: 1, twitter_tweet_id: "138032", word_count: nil, character_count: 1, hour: 2},
  {tweet_text: "lkj ", twitter_account_id: 1, twitter_tweet_id: "6289741", word_count: nil, character_count: 140, hour: 6},
  {tweet_text: ";laksjdf lkajs ;fla sf", twitter_account_id: 1, twitter_tweet_id: "8743930", word_count: nil, character_count: 3, hour: 0},
  {tweet_text: "lajsdf o aoioaije aijpao", twitter_account_id: 1, twitter_tweet_id: "19848032", word_count: nil, character_count: 167, hour: 2},
  {tweet_text: "lkj ", twitter_account_id: 1, twitter_tweet_id: "6741", word_count: nil, character_count: 44, hour: 6},
  {tweet_text: ";laksjdf lkajs ;fla sf", twitter_account_id: 1, twitter_tweet_id: "87930", word_count: nil, character_count: 25, hour: 0}
])
TwitterAccount.create!([
  {twitter_uid: "12341", user_id: 1, token: nil, secret: nil, username: nil, time_zone: nil, num_followers: nil, total_num_tweets: nil}
])
TwitterResult.create!([
  {most_used_words: nil, least_used_words: nil, early_bird: false, avg_tweet_length: nil, num_followers: nil, total_tweets: nil, followers_most_used_words: nil, followers_least_used_words: nil, followers_early_bird: nil, followers_avg_tweet_length: nil, followers_avg_num_followers: nil, followers_avg_total_tweets: nil, char_per_tweet: nil, user_id: 1},
  {most_used_words: nil, least_used_words: nil, early_bird: nil, avg_tweet_length: nil, num_followers: nil, total_tweets: nil, followers_most_used_words: nil, followers_least_used_words: nil, followers_early_bird: nil, followers_avg_tweet_length: nil, followers_avg_num_followers: nil, followers_avg_total_tweets: nil, char_per_tweet: "{\"char_1_20\":2,\"char_21_40\":1,\"char_41_60\":1,\"char_61_80\":0,\"char_81_100\":0,\"char_101_120\":0,\"char_121_140\":1}", user_id: nil}
])
User.create!([
  {email: "asdf@asdf.com", password_digest: "$2a$10$DsOdduaGBtsryj53sC6xWe6slJ.yTWDegsA0yANBjexVok6iVGcAe", name: "Asdf"}
])